android_binary(
    name = "app",
    manifest = "AndroidManifest.xml",
    deps = ["//fraikin_home_automation/android_app/src/main/java/example/hello_world:greeter_activity"],
)
# Install the app with bazel mobile-install //fraikin_home_automation/android_app/src/main:app
