filegroup(
    name = "arduino_deployment_core_template",
    srcs = ["arduino_deployment_core_cpp.jinja"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "raspi_deployment_core_template",
    srcs = ["raspi_deployment_core_py.jinja"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "data_type_h_template",
    srcs = ["data_type_h.jinja"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "data_type_py_template",
    srcs = ["data_type_py.jinja"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "interface_h_template",
    srcs = ["interface_h.jinja"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "interface_py_template",
    srcs = ["interface_py.jinja"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "arduino_interface_sender",
    srcs = [
        "arduino_interface_sender_cpp.jinja",
        "arduino_interface_sender_h.jinja",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "arduino_interface_receiver",
    srcs = [
        "arduino_interface_receiver_cpp.jinja",
        "arduino_interface_receiver_h.jinja",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "arduino_interface_bluetooth_sender",
    srcs = [
        "arduino_interface_bluetooth_sender_cpp.jinja",
        "arduino_interface_bluetooth_sender_h.jinja",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "arduino_interface_bluetooth_receiver",
    srcs = [
        "arduino_interface_bluetooth_receiver_cpp.jinja",
        "arduino_interface_bluetooth_receiver_h.jinja",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "arduino_interface_funk_sender",
    srcs = [
        "arduino_interface_funk_sender_cpp.jinja",
        "arduino_interface_funk_sender_h.jinja",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "arduino_interface_funk_receiver",
    srcs = [
        "arduino_interface_funk_receiver_cpp.jinja",
        "arduino_interface_funk_receiver_h.jinja",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "raspi_serial_interface_sender",
    srcs = [
        "raspi_serial_interface_sender_py.jinja",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "raspi_serial_interface_receiver",
    srcs = [
        "raspi_serial_interface_receiver_py.jinja",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "raspi_app_interface_sender_receiver",
    srcs = [
        "raspi_app_interface_sender_receiver_py.jinja",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "app_interface",
    srcs = [
        "app_interface_java.jinja",
    ],
    visibility = ["//visibility:public"],
)
