filegroup(
    name = "arduino_deployment_core_template",
    srcs = ["arduino_deployment_core_cpp.jinja"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "raspi_deployment_core_template",
    srcs = ["raspi_deployment_core_py.jinja"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "data_type_h_template",
    srcs = ["data_type_h.jinja"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "data_type_py_template",
    srcs = ["data_type_py.jinja"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "interface_h_template",
    srcs = ["interface_h.jinja"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "interface_py_template",
    srcs = ["interface_py.jinja"],
    visibility = ["//visibility:public"],
)
